// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzpmtccuykspebhwvclk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cG10Y2N1eWtzcGViaHd2Y2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzgxMDAsImV4cCI6MjA3NDQ1NDEwMH0.PlosLN8EXkeWZhHfjMluZRtyq8L8iMWYMsVpxhGt1Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});